apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: vlan23
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "8"
spec:
  config: '{ "name":"vlan23", "type":"ovn-k8s-cni-overlay", "cniVersion":"0.4.0", "physicalNetworkName":"trunk-net", "topology":"localnet", "netAttachDefName":"default/vlan23", "vlanID":23, "mtu":1500 }'
