apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: br-ex-network
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  desiredState:
    ovn:
      bridge-mappings:
      - bridge: br-ex
        localnet: vlan26-net
        state: present
