apiVersion: machineconfiguration.openshift.io/v1
kind: MachineConfig
metadata:
  labels:
    machineconfiguration.openshift.io/role: worker
  name: 11-worker-bond0
spec:
  config:
    ignition:
      version: 3.2.0
    storage:
      files:
      - contents:
          source: data:;base64,W2Nvbm5lY3Rpb25dCmlkPWJvbmQwCnR5cGU9Ym9uZAppbnRlcmZhY2UtbmFtZT1ib25kMAphdXRvY29ubmVjdD10cnVlCmNvbm5lY3Rpb24uYXV0b2Nvbm5lY3Qtc2xhdmVzPTEKYXV0b2Nvbm5lY3QtcHJpb3JpdHk9MjAKCltldGhlcm5ldF0KbXR1PTkwMDAKCltib25kXQptb2RlPWFjdGl2ZS1iYWNrdXAKbWlpbW9uPTEwMAoKW2lwdjRdCm1ldGhvZD1hdXRvCgpbaXB2Nl0KbWV0aG9kPWF1dG8K
        path: /etc/NetworkManager/system-connections/bond0.nmconnection
        filesystem: root
        mode: 0600
      - contents:
          source: data:;base64,W2Nvbm5lY3Rpb25dCmlkPWVuczE5Mgp0eXBlPWV0aGVybmV0CmludGVyZmFjZS1uYW1lPWVuczE5MgptYXN0ZXI9Ym9uZDAKc2xhdmUtdHlwZT1ib25kCmF1dG9jb25uZWN0PXRydWUKYXV0b2Nvbm5lY3QtcHJpb3JpdHk9MjAKCltldGhlcm5ldF0KbXR1PTkwMDAK
        path: /etc/NetworkManager/system-connections/ens192.nmconnection
        filesystem: root
        mode: 0600
      - contents:
          source: data:;base64,W2Nvbm5lY3Rpb25dCmlkPWVuczIyNAp0eXBlPWV0aGVybmV0CmludGVyZmFjZS1uYW1lPWVuczIyNAptYXN0ZXI9Ym9uZDAKc2xhdmUtdHlwZT1ib25kCmF1dG9jb25uZWN0PXRydWUKYXV0b2Nvbm5lY3QtcHJpb3JpdHk9MjAKCltldGhlcm5ldF0KbXR1PTkwMDAK
        path: /etc/NetworkManager/system-connections/ens224.nmconnection
        filesystem: root
        mode: 0600
