apiVersion: nmstate.io/v1
kind: NodeNetworkConfigurationPolicy
metadata:
  name: extra-dns-config
spec:
  desiredState:
    dns-resolver:
      config:
        server:
          - 192.168.165.10
  nodeSelector:
    node-role.kubernetes.io/worker: ''
