---
apiVersion: v1
kind: Namespace
metadata:
  name: app1-dev
  labels:
    companycode: 1234
    environmenttype: dev
---
kind: LimitRange
apiVersion: v1
metadata:
  name: default-limit-range
  namespace: app1-dev
spec:
  limits:
  - default:
      memory: 2Gi
      cpu: 1
    defaultRequest:
      memory: 256Mi
      cpu: 500m
    type: Container
---
kind: ResourceQuota
apiVersion: v1
metadata:
  name: quota
  namespace: app1-dev
spec:
  hard:
    limits.cpu: 4
    limits.memory: 8Gi
    pods: 20
    requests.cpu: 2
    requests.memory: 4Gi
    persistentvolumeclaims: 10
    secrets: 20
    services: 20
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-stephane-admin
  namespace: app1-dev
subjects:
- kind: User
  name: stephane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-dominique-edit
  namespace: app1-dev
subjects:
- kind: User
  name: dominique
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-phil-view
  namespace: app1-dev
subjects:
- kind: User
  name: phil
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-ingress
  namespace: app1-dev
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          policy-group.network.openshift.io/ingress: ''
  podSelector: {}
  policyTypes:
  - Ingress
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-from-openshift-monitoring
  namespace: app1-dev
spec:
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          network.openshift.io/policy-group: monitoring
  podSelector: {}
  policyTypes:
  - Ingress
---
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: allow-same-namespace
  namespace: app1-dev
spec:
  podSelector: {}
  ingress:
  - from:
    - podSelector: {}
