apiVersion: observability.openshift.io/v1alpha1
kind: UIPlugin
metadata:
  name: logging
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  logging:
    logsLimit: 50
    lokiStack:
      name: logging-loki
    schema: otel
    timeout: 30s
  type: Logging