apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: loki-operator
  namespace: openshift-operators-redhat 
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  upgradeStrategy: Default