apiVersion: loki.grafana.com/v1
kind: LokiStack
metadata:
  name: logging-loki
  namespace: openshift-logging
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  managementState: Managed
  size: 1x.demo
  storage:
    schemas:
    - effectiveDate: "2025-10-01"
      version: v13
    secret:
      name: logging-loki-odf
      type: s3
    tls:
      caKey: service-ca.crt
      caName: openshift-service-ca.crt
  storageClassName: gp3-csi
  tenants:
    mode: openshift-logging