apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-storage-vnx5n
  namespace: openshift-storage
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  targetNamespaces:
  - openshift-storage
  upgradeStrategy: Default