apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: policy-secret
  namespace: acm-policy
  annotations:
    policy.open-cluster-management.io/categories: cluster-config
spec:
  remediationAction: enforce
  disabled: false
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: policy-secret
        spec:
          remediationAction: inform
          severity: low
          namespaceSelector:
            exclude:
              - kube-*
            include:
              - default
          object-templates:
            - complianceType: musthave
              objectDefinition:
                apiVersion: v1
                kind: Secret
                metadata:
                  name: github
                  namespace: openshift-config
                type: Opaque
                data:
                  clientSecret: '{{ fromSecret "openshift-monitoring" "alertmanager-main" "alertmanager.yaml" }}'
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: binding-policy-secret
placementRef:
  name: placement-policy-secret
  kind: PlacementRule
  apiGroup: apps.open-cluster-management.io
subjects:
- name: policy-secret
  kind: Policy
  apiGroup: policy.open-cluster-management.io
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: placement-policy-secret
spec:
  clusterConditions:
  - status: "True"
    type: ManagedClusterConditionAvailable
  clusterSelector:
    matchExpressions:
      - key: ocp-secret
        operator: In
        values:
          - "true"