apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: mem-usage-tester
  namespace: tester
spec:
  groups:
  - name: mem-usage
    rules:
    - alert: ContainerMemoryUsage
      expr: (sum(container_memory_working_set_bytes) BY (instance, name) / sum(container_spec_memory_limit_bytes > 0) BY (instance, name) * 100) > 10
      for: 2m
      labels:
        severity: warning
      annotations:
        summary: Container Memory usage (instance {{ $labels.instance }})
        description: "Container Memory usage is above 10%\n  VALUE = {{ $value }}\n  LABELS = {{ $labels }}"
