---
apiVersion: v1
kind: Namespace
metadata:
  name: app1-dev
  labels:
    companycode: 1234
    environmenttype: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-stephane-admin
  namespace: app1-dev
subjects:
- kind: User
  name: stephane
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-dominique-edit
  namespace: app1-dev
subjects:
- kind: User
  name: dominique
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: edit
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app1-dev-phil-view
  namespace: app1-dev
subjects:
- kind: User
  name: phil
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: view
  apiGroup: rbac.authorization.k8s.io
