apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
bases:
- ../../base
namespace: app1-staging
nameSuffix: "-staging"
commonLabels:
  environment: staging
patches:
  - patch: |-
      kind: ResourceQuota
      apiVersion: v1
      metadata:
        name: quota
      spec:
        hard:
          limits.cpu: 6
          limits.memory: '12Gi'
