apiVersion: policy.open-cluster-management.io/v1
kind: PolicyGenerator
metadata:
  name: node-maint-operator
policyDefaults:
  namespace: acm-policies
  placement:
    labelSelector:
      matchExpressions:
        - key: vendor
          operator: In
          values:
            - "OpenShift"
policies:
  - name: node-maint-operator
    remediationAction: inform 
    manifests:
      - path: manifests/