apiVersion: external-secrets.io/v1
kind: ClusterSecretStore
metadata:
  name: aws-cluster-secretstore
spec:
  provider:
    aws:
      auth:
        secretRef:
          accessKeyIDSecretRef:
            key: aws_access_key_id
            name: aws-cloud-credentials
            namespace: external-secrets-operator
          secretAccessKeySecretRef:
            key: aws_secret_access_key
            name: aws-cloud-credentials
            namespace: external-secrets-operator
      region: us-east-2
      service: SecretsManager