apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: openshift-compliance
  namespace: openshift-compliance
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  upgradeStrategy: Default