apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  name: install-rhsso-instance
  namespace: open-cluster-management
spec:
  disabled: false
  remediationAction: enforce
  policy-templates:
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhsso-operator-ns
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                 apiVersion: keycloak.org/v1alpha1
                 kind: Keycloak
                 metadata:
                   name: rhsso
                   namespace: rhsso
                   labels:
                     app: rhsso
                 spec:
                   instances: 1
                   externalAccess:
                     enabled: true
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhsso-realm
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                 apiVersion: keycloak.org/v1alpha1
                 kind: KeycloakRealm
                 metadata:
                   labels:
                     app: openshift
                   name: openshift-realm
                   namespace: rhsso
                 spec:
                   realm:
                     id: openshift
                     realm: openshift
                     enabled: true
                     displayName: Openshift Authentication Realm
                   instanceSelector:
                     matchLabels:
                       app: rhsso
    - objectDefinition:
        apiVersion: policy.open-cluster-management.io/v1
        kind: ConfigurationPolicy
        metadata:
          name: rhsso-client
        spec:
          remediationAction: inform
          severity: high
          object-templates:
            - complianceType: musthave
              objectDefinition:
                 apiVersion: keycloak.org/v1alpha1
                 kind: KeycloakClient
                 metadata:
                   name: openshift-client
                   namespace: rhsso
                   labels:
                     app: rhsso
                 spec:
                   realmSelector:
                     matchLabels:
                       app: openshift
                   client:
                     clientId: openshift
                     realm": "openshift"
                     secret: 5e9326ee-ac8d-40bf-9060-e91dbe9d9000
                     clientAuthenticatorType: client-secret
                     consentRequired: false
                     standardFlowEnabled: true
                     implicitFlowEnabled: false
                     directAccessGrantsEnabled: true
                     redirectUris:
                       - "https://keycloak.example.com/auth/realms/master/protocol/openid-connect/token"
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  name: install-rhsso-instance-binding-placement
  namespace: open-cluster-management
placementRef:
  name: local-cluster-binding-placement
  apiGroup: apps.open-cluster-management.io
  kind: PlacementRule
subjects:
  - name: install-rhsso-instance
    apiGroup: policy.open-cluster-management.io
    kind: Policy
