apiVersion: forklift.konveyor.io/v1beta1
kind: ForkliftController
metadata:
  name: forklift-controller
  namespace: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  feature_ui_plugin: "true"
  feature_validation: "true"
  feature_volume_populator: "true"