apiVersion: v1
kind: Namespace
metadata:
  labels:
    openshift.io/cluster-monitoring: "true"
  name: openshift-mtv
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  finalizers:
  - kubernetes
