FROM registry.access.redhat.com/ubi8:8.5

MAINTAINER Phil Thomson <pthomson@redhat.com>

RUN yum -y install cups httpd

ENV MY_NAME="John Doe"
ENV MY_DOG=Rex\ The\ Dog
ENV MY_CAT=fluffy
ENV SERVER=bob

EXPOSE 631
EXPOSE 80

CMD ["/usr/sbin/cupsd", "-f"]

