kind: LokiStack
apiVersion: loki.grafana.com/v1
metadata:
 name: lokistack
 namespace: openshift-logging
spec:
 managementState: Managed
 size: 1x.demo
 storage:
   schemas:
     - effectiveDate: '2024-10-01'
       version: v13
   secret:
     name: logging-loki-aws
     type: s3
 storageClassName: gp3-csi
 tenants:
   mode: openshift-logging