kind: Secret
apiVersion: v1
metadata:
  name: alertmanager-main
  namespace: openshift-monitoring
  labels:
    app.kubernetes.io/component: alert-router
    app.kubernetes.io/instance: main
    app.kubernetes.io/managed-by: cluster-monitoring-operator
    app.kubernetes.io/name: alertmanager
    app.kubernetes.io/part-of: openshift-monitoring
    app.kubernetes.io/version: 0.28.1
data:
  alertmanager.yaml: {{ .Values.alertmanagerConfig | b64enc }}
type: Opaque
