kind: ConfigMap
apiVersion: v1
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/managed-by: openshift-gitops
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: | 
    'g, system:cluster-admins, role:admin'
    'g, phil, role:admin'
  policy.default: 'role:readonly'
  scopes: '[groups]'
